# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/wedemo"
        descriptionTag: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
server:
  address: ":8080"
mq:
  url: "amqp://guest:guest@localhost:5672/"
redis:
  default:
    address: "127.0.0.1:6379"
    db: 0
    pass: ""
    idleTimeout: "300s"
    maxIdle: 10
    maxActive: 100
    minIdle: 10
mysql:
  default:
    host: "127.0.0.1"
    user: "root"
    password: "yourpassword"
    dbName: "yourdb"
    port: 3306
    charset: "utf8mb4"
    timeout: "30s"
