# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
        descriptionTag: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
server:
  address: ":9090"
mq:
  url: "amqp://guest:guest@localhost:5672/"
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  minIdle: 10
  maxIdle: 10
  maxActive: 100
  idleTimeout: "300s"
